all:
  children:
    hypervisors:
      hosts:
        wks1:
          ansible_host: localhost
    infra_sigec:
      vars:
        ansible_user: ops
        ansible_ssh_extra_args: >
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
          -o GlobalKnownHostsFile=/dev/null

      children:

        infra_ctrl:
          hosts:
            test_ctrl:
              ansible_host: 192.168.100.203

        infra_keepalived:
          hosts:
            test_keepalived1:
              ansible_host: 192.168.100.148
              keepalived_vrrp_state: master
            test_keepalived2: 
              ansible_host: 192.168.100.221
              keepalived_vrrp_state: backup

        infra_apache:
          hosts:
            test_apache1:
              ansible_host: 192.168.100.146
            test_apache2:
              ansible_host: 192.168.100.202
            test_apache3:
              ansible_host: 192.168.100.211

